In [4]:
import pandas as pd

In [5]:
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).

In [6]:
features = pd.read_csv('/content/Drive/MyDrive/Features data set.csv')
stores = pd.read_csv('/content/Drive/MyDrive/stores data-set.csv')
sales = pd.read_csv('/content/Drive/MyDrive/sales data-set.csv')

### Business Question
Which departments generate the highest and lowest total sales?

In [32]:
dept_sales = (
    sales.groupby('Dept')['Weekly_Sales']
    .sum()
    .sort_values(ascending=False)
)

dept_sales.head()

Dept
92    4.839433e+08
95    4.493202e+08
38    3.931181e+08
72    3.057252e+08
90    2.910685e+08
Name: Weekly_Sales, dtype: float64

### Insight

**Insight:** Department 92 leads total sales at approximately $483.94M, followed by Departments 95 and 38.

### Business Question

Which departments generate the lowest total sales?

In [8]:
dept_sales = sales.groupby('Dept')['Weekly_Sales'].sum()
dept_sales.sort_values(ascending=True).head()

Dept
47    -4962.93
43       14.32
39      177.98
78     1714.71
51    30572.83
Name: Weekly_Sales, dtype: float64

### Insight

**Insight:** Department 47 recorded negative total sales of $4,962.93, while Departments 43 and 39 generated minimal sales.

### Business Question

Which departments have the highest average weekly sales?

In [33]:
dept_avg = sales.groupby('Dept')['Weekly_Sales'].mean()
dept_avg.sort_values(ascending = False).head().round(2)

Dept
92    75204.87
95    69824.42
38    61090.62
72    50566.52
65    45441.71
Name: Weekly_Sales, dtype: float64

### Insight

**Insight:** Department 92 leads average weekly sales at 75,204.87, followed by Departments 95 and 38.

### Business Question

Which departments have the lowest average weekly sales?

In [34]:
dept_avg = sales.groupby('Dept')['Weekly_Sales'].mean().reset_index(name='dept_avg')
dept_avg.sort_values(by='dept_avg',ascending = True).head().round(2)

    Dept  dept_avg
45    47     -7.68
41    43      1.19
63    78      7.30
37    39     11.12
49    51     21.93

### Insight

**Insight:** Department 47 has the lowest average weekly sales at -7.68, while Departments 43 and 78 also show minimal average sales.

### Business Question

Which departments have the highest variability in weekly sales?

In [35]:
dept_std = sales.groupby('Dept')['Weekly_Sales'].std()
dept_std.sort_values(ascending=False).head().round(2)

Dept
92    49413.73
72    44710.98
95    38200.54
90    32462.02
7     27985.08
Name: Weekly_Sales, dtype: float64

### Insight

**Insight:** Department 92 has the highest weekly sales variability at 49,413.73, followed by Departments 72 and 95, indicating greater week-to-week fluctuations.

### Business Question

Which departments have the lowest variability in weekly sales?

In [36]:
dept_std = sales.groupby('Dept')['Weekly_Sales'].std().reset_index(name='dept_std')
dept_std.sort_values(by='dept_std',ascending=True).head().set_index('Dept').round(2)

      dept_std
Dept
43        1.03
39        9.51
78       10.40
45       24.96
51       29.15

### Insight

**Insight:** Department 43 has the lowest sales variability at 1.03, followed by Departments 39 and 78, indicating highly consistent weekly sales.

### Business Question

Which departments combine strong average sales with relatively low variability?

In [37]:
dept_risk = dept_avg.merge(dept_std,on='Dept')
strong_stable_dept = dept_risk.query(
    "dept_avg > 20000 & dept_std < 30000"
)
strong_stable_dept.sort_values(by='dept_avg',ascending=False).head().set_index('Dept').round(2)

      dept_avg  dept_std
Dept
38    61090.62  23966.91
65    45441.71   7086.89
40    44900.70  21903.88
2     43607.02  25176.76
91    33687.91  26247.46

### Insight

**Insight:** Department 38 leads the strong-and-stable group in average sales, while Department 65 combines strong sales with the lowest variability.

### Business Question

Which departments have the lowest relative variability in weekly sales?

In [38]:
dept_risk['cv'] = dept_risk['dept_std'] / dept_risk['dept_avg']
dept_risk.sort_values(by='cv', ascending=True).head().round(2)

    Dept  dept_avg  dept_std     cv
45    47     -7.68    307.88 -40.08
57    65  45441.71   7086.89   0.16
35    37   3111.08    887.65   0.29
36    38  61090.62  23966.91   0.39
38    40  44900.70  21903.88   0.49

In [39]:
dept_risk_positive = dept_risk.query("dept_avg > 0")

print(
    dept_risk_positive
    .sort_values(by='cv', ascending=False)
    .head().round(2)
)

    Dept  dept_avg  dept_std    cv
55    59    694.46   1991.36  2.87
80    99    415.49   1099.73  2.65
16    18   7336.94  13837.76  1.89
53    56   3833.71   5978.35  1.56
63    78      7.30     10.40  1.43

### Insight

**Insight:** Departments 59 and 99 have the highest relative variability, but their low average sales suggest that CV should be interpreted alongside sales volume.

### Business Question

Which departments have the highest number of negative sales records?

In [41]:
negative_dept = sales[sales['Weekly_Sales']<0].groupby('Dept').size().reset_index(name='negative_counts')
negative_dept.sort_values(by='negative_counts',ascending=False).head().set_index('Dept')

      negative_counts
Dept
47                254
18                180
54                146
19                 87
94                 77

### Insight

**Insight:** Department 47 has the highest number of negative-sales records at 254, followed by Departments 18 and 54.

### Business Question

Which departments have the largest total negative-sales amount?

In [17]:
negative_sales_amount = sales[sales['Weekly_Sales']<0].groupby('Dept')['Weekly_Sales'].sum().reset_index().sort_values(by='Weekly_Sales').head().set_index('Dept')
negative_sales_amount

      Weekly_Sales
Dept
47       -53188.06
6         -5841.64
54        -4829.81
80        -4231.48
72        -3047.58

### Insight

**Insight:** Department 47 has the largest total negative-sales amount at -$53,188.06, substantially exceeding the other departments shown.

### Business Question

How do department sales vary across years?

In [18]:
sales['Date'] = pd.to_datetime(
    sales['Date'],dayfirst=True
)
sales['Year'] = sales['Date'].dt.year

In [43]:
dept_year_sales = sales.groupby(['Year','Dept'])['Weekly_Sales'].sum().reset_index()
dept_year_sales.sort_values(by=['Year','Dept'],ascending=[True,True]).set_index('Year')

      Dept  Weekly_Sales
Year
2010     1  4.284353e+07
2010     2  9.405293e+07
2010     3  2.509114e+07
2010     4  5.557729e+07
2010     5  5.177156e+07
2010     6  1.237954e+07
2010     7  5.842404e+07
2010     8  6.536836e+07
2010     9  4.312974e+07
2010    10  3.921423e+07
2010    11  3.218926e+07
2010    12  9.228136e+06
2010    13  6.728259e+07
2010    14  3.413632e+07
2010    16  3.191970e+07
2010    17  2.345061e+07
2010    18  1.554719e+07
2010    19  2.412333e+06
2010    20  1.157589e+07
2010    21  1.183476e+07
2010    22  2.082589e+07
2010    23  4.800848e+07
2010    24  1.244356e+07
2010    25  1.991965e+07
2010    26  1.588014e+07
2010    27  3.103706e+06
2010    28  1.432578e+06
2010    29  1.056289e+07
2010    30  7.864722e+06
2010    31  5.067522e+06
2010    32  1.476493e+07
2010    33  1.274983e+07
2010    34  2.929150e+07
2010    35  5.261722e+06
2010    36  3.650176e+06
2010    37  2.781083e+06
2010    38  1.288553e+08
2010    39  3.892000e+01
2010    40  9.641509e+07
2010    41  3.566715e+06
2010    42  1.088041e+07
2010    43  1.750000e+00
2010    44  8.765188e+06
2010    45  2.079783e+04
2010    46  4.257488e+07
2010    47 -2.315950e+03
2010    48  5.693381e+05
2010    49  1.201488e+07
2010    50  1.363291e+06
2010    51  2.438996e+04
2010    52  4.303046e+06
2010    54  3.586228e+05
2010    55  2.420469e+07
2010    56  7.563504e+06
2010    58  6.169731e+06
2010    59  2.531748e+06
2010    60  6.343142e+05
2010    65  2.356594e+06
2010    67  1.658868e+07
2010    71  1.063541e+07
2010    72  1.105091e+08
2010    74  3.039732e+07
2010    77  7.970000e+00
2010    78  1.087670e+03
2010    79  4.808053e+07
2010    80  2.380621e+07
2010    81  3.298665e+07
2010    82  3.214679e+07
2010    83  6.983036e+06
2010    85  5.195689e+06
2010    87  2.540269e+07
2010    90  9.340488e+07
2010    91  7.142537e+07
2010    92  1.558376e+08
2010    93  5.195455e+07
2010    94  6.274761e+07
2010    95  1.498584e+08
2010    96  2.350948e+07
2010    97  2.948267e+07
2010    98  1.372437e+07
2010    99  1.568000e+02
2011     1  4.534931e+07
2011     2  1.015053e+08
2011     3  2.701822e+07
2011     4  6.056611e+07
2011     5  5.036340e+07
2011     6  1.008493e+07
2011     7  5.920394e+07
2011     8  7.003633e+07
2011     9  4.508026e+07
2011    10  4.289309e+07
2011    11  3.380392e+07
2011    12  9.344185e+06
2011    13  7.052816e+07
2011    14  3.502576e+07
2011    16  3.031971e+07
2011    17  2.353410e+07
2011    18  1.590581e+07
2011    19  2.394082e+06
2011    20  1.173379e+07
2011    21  1.141181e+07
2011    22  2.157368e+07
2011    23  5.023485e+07
2011    24  1.232673e+07
2011    25  2.062956e+07
2011    26  1.578451e+07
2011    27  3.308765e+06
2011    28  1.364585e+06
2011    29  1.093182e+07
2011    30  7.669664e+06
2011    31  5.312722e+06
2011    32  1.495831e+07
2011    33  1.250468e+07
2011    34  2.876885e+07
2011    35  5.642381e+06
2011    36  4.004827e+06
2011    37  2.879915e+06
2011    38  1.432613e+08
2011    39  1.980000e+00
2011    40  1.033216e+08
2011    41  4.177032e+06
2011    42  1.190231e+07
2011    43  7.070000e+00
2011    44  9.302019e+06
2011    45  1.578313e+04
2011    46  4.704046e+07
2011    47 -3.742290e+03
2011    48  7.869548e+05
2011    49  1.322627e+07
2011    50  1.498399e+06
2011    51  5.840730e+03
2011    52  4.454167e+06
2011    54  1.079005e+05
2011    55  2.290391e+07
2011    56  7.605944e+06
2011    58  5.281367e+06
2011    59  1.313469e+06
2011    60  7.575648e+05
2011    65  2.147673e+06
2011    67  1.711504e+07
2011    71  1.085635e+07
2011    72  1.149085e+08
2011    74  3.194442e+07
2011    77  4.078144e+04
2011    78  3.975200e+02
2011    79  5.068125e+07
2011    80  2.622204e+07
2011    81  3.610738e+07
2011    82  3.789979e+07
2011    83  6.983100e+06
2011    85  5.031147e+06
2011    87  3.117816e+07
2011    90  1.079482e+08
2011    91  7.886816e+07
2011    92  1.764763e+08
2011    93  5.822909e+07
2011    94  6.880016e+07
2011    95  1.615699e+08
2011    96  2.675970e+07
2011    97  3.261287e+07
2011    98  1.459991e+07
2011    99  2.631143e+05
2012     1  3.544593e+07
2012     2  8.505299e+07
2012     3  2.378310e+07
2012     4  5.100335e+07
2012     5  3.347240e+07
2012     6  5.956193e+06
2012     7  3.784958e+07
2012     8  5.887608e+07
2012     9  4.018326e+07
2012    10  3.579007e+07
2012    11  2.733609e+07
2012    12  8.187799e+06
2012    13  5.951081e+07
2012    14  2.653259e+07
2012    16  2.943128e+07
2012    17  1.833511e+07
2012    18  5.444486e+06
2012    19  2.009768e+06
2012    20  1.003996e+07
2012    21  8.818067e+06
2012    22  1.732354e+07
2012    23  3.993699e+07
2012    24  9.577296e+06
2012    25  1.656201e+07
2012    26  1.223536e+07
2012    27  2.484865e+06
2012    28  9.879910e+05
2012    29  8.514888e+06
2012    30  6.254995e+06
2012    31  3.813140e+06
2012    32  1.097572e+07
2012    33  9.629458e+06
2012    34  2.516327e+07
2012    35  4.568672e+06
2012    36  3.054511e+06
2012    37  2.356245e+06
2012    38  1.210016e+08
2012    39  1.370800e+02
2012    40  8.919934e+07
2012    41  2.856519e+06
2012    42  1.043657e+07
2012    43  5.500000e+00
2012    44  7.382406e+06
2012    45  8.356670e+03
2012    46  3.872907e+07
2012    47  1.095310e+03
2012    48  9.865116e+05
2012    49  1.133175e+07
2012    50  1.291507e+06
2012    51  3.421400e+02
2012    52  3.329724e+06
2012    54  4.977137e+04
2012    55  1.286186e+07
2012    56  7.342075e+06
2012    58  4.804666e+06
2012    59  3.951774e+05
2012    60  6.131420e+05
2012    65  1.993897e+06
2012    67  1.417706e+07
2012    71  8.891262e+06
2012    72  8.030760e+07
2012    74  2.644025e+07
2012    77  8.554860e+03
2012    78  2.295200e+02
2012    79  4.263476e+07
2012    80  2.174581e+07
2012    81  3.045800e+07
2012    82  2.950049e+07
2012    83  6.022695e+06
2012    85  3.483860e+06
2012    87  2.917922e+07
2012    90  8.971536e+07
2012    91  6.648817e+07
2012    92  1.516294e+08
2012    93  4.951503e+07
2012    94  5.836468e+07
2012    95  1.378918e+08
2012    96  2.356474e+07
2012    97  2.740097e+07
2012    98  1.150465e+07
2012    99  9.487876e+04

In [20]:
top_dept_year = dept_year_sales.sort_values(by='Weekly_Sales',ascending=False).head(10)
top_dept_year.set_index('Year')

      Dept  Weekly_Sales
Year
2011    92  1.764763e+08
2011    95  1.615699e+08
2010    92  1.558376e+08
2012    92  1.516294e+08
2010    95  1.498584e+08
2011    38  1.432613e+08
2012    95  1.378918e+08
2010    38  1.288553e+08
2012    38  1.210016e+08
2011    72  1.149085e+08

### Insight

**Insight:** Department 92 in 2011 had the highest Year–Department sales among the top 10 combinations. Departments 92, 95, and 38 repeatedly appear among the strongest combinations across years.

### Business Question

Which Year–Department combinations have the lowest total weekly sales?

In [21]:
top_dept_year = dept_year_sales.sort_values(by='Weekly_Sales',ascending=True).head(10)
top_dept_year.set_index('Year')

      Dept  Weekly_Sales
Year
2011    47      -3742.29
2010    47      -2315.95
2010    43          1.75
2011    39          1.98
2012    43          5.50
2011    43          7.07
2010    77          7.97
2010    39         38.92
2012    39        137.08
2010    99        156.80

### Insight

**Insight:** Department 47 recorded the lowest Year–Department sales in both 2011 and 2010, with negative totals. Departments 43 and 39 also repeatedly appear among the weakest-performing combinations.

## Business Question

Which store–department combinations generate the highest total weekly sales?

In [49]:
store_dept_sales = sales.groupby(['Store','Dept'])['Weekly_Sales'].sum().reset_index().sort_values(by='Weekly_Sales',ascending=False)
store_dept_sales.head(10).set_index('Store')

       Dept  Weekly_Sales
Store
14       92   26101497.71
2        92   23572153.03
20       92   23542625.04
13       92   23170876.20
4        92   22789210.43
20       95   21537795.62
4        95   21054815.74
27       92   20952094.22
14       95   20655911.35
2        95   20533191.52

### Insight

**Insight:** Store 14 and Department 92 form the highest-selling Store–Department combination at 26,101,497.71. Department 92 dominates the top-performing combinations, appearing in 7 of the top 10.

## Business Question

Which store–department combinations generate the lowest total weekly sales?

In [23]:
store_dept_sales = sales.groupby(['Store','Dept'])['Weekly_Sales'].sum().reset_index().sort_values(by='Weekly_Sales',ascending=True)
store_dept_sales.head(10).set_index('Store')

       Dept  Weekly_Sales
Store
35       47      -3567.18
1        47      -2562.00
10       47      -2329.00
42       72      -1209.93
45       47      -1061.04
16       47      -1039.08
12       47       -965.78
34       47       -947.03
6        47       -756.42
23       47       -551.50

### Insight

**Insight:** Store 35 and Department 47 have the lowest Store–Department sales at -3,567.18. Department 47 appears in 9 of the bottom 10 combinations, reinforcing its unusually poor sales performance.

## Business Question

Which department is the top-performing department within each store?

In [24]:
store_dept_sales.loc[
    store_dept_sales.groupby('Store')['Weekly_Sales'].idxmax()
].set_index('Store')

       Dept  Weekly_Sales
Store
1        92   19370632.64
2        92   23572153.03
3        38   15529566.07
4        92   22789210.43
5        38    7893570.24
6        92   14160545.90
7        72    6447844.96
8        95    9002059.31
9        38   11184287.78
10       72   20410926.56
11       95   11080680.91
12        2   10652763.01
13       92   23170876.20
14       92   26101497.71
15       38    7517821.66
16       38    7447254.23
17       38   11059588.03
18       38    9339684.03
19       92   16261990.45
20       92   23542625.04
21        2    6832625.68
22       38   10015536.66
23       72   10988695.25
24       92   17429136.57
25       38    6381753.99
26       38   14800243.10
27       92   20952094.22
28       92   14083635.33
29       38    6075233.36
30       38    8761108.01
31       92   18162446.96
32       92   14317578.85
33       92    4894555.79
34       95    9902061.88
35       72   12631448.67
36       94    6774217.61
37       38    9922606.19
38       38    7858677.16
39       92   15748047.97
40       92   13796032.72
41       92   16563355.96
42       92   11940182.35
43       92   11961401.01
44       38    6546336.18
45       38    7613685.44

### Insight

**Insight:** Department 92 is the leading department across many stores, while Departments 38 and 72 also emerge as top-performing departments in multiple stores.

## Buisness Question
Which departments contribute the most sales within each year?

In [25]:
dept_sales = sales.groupby(['Dept','Year'])['Weekly_Sales'].sum().reset_index()
dept_sales_year = dept_sales.loc[dept_sales.groupby('Year')['Weekly_Sales'].idxmax()].sort_values(by='Year')
dept_sales_year.set_index('Dept')

      Year  Weekly_Sales
Dept
92    2010  1.558376e+08
92    2011  1.764763e+08
92    2012  1.516294e+08

### Insight
Department 92 remained the top-performing department across all three years, reaching its highest sales in 2011 before declining in 2012.

### Business Question

Which departments had the largest increase or decrease in sales from 2010 to 2012?

In [26]:
dept_year_sales = sales.groupby(['Dept','Year'])['Weekly_Sales'].sum().unstack()
dept_year_sales

Year          2010          2011          2012
Dept
1     4.284353e+07  4.534931e+07  3.544593e+07
2     9.405293e+07  1.015053e+08  8.505299e+07
3     2.509114e+07  2.701822e+07  2.378310e+07
4     5.557729e+07  6.056611e+07  5.100335e+07
5     5.177156e+07  5.036340e+07  3.347240e+07
...            ...           ...           ...
95    1.498584e+08  1.615699e+08  1.378918e+08
96    2.350948e+07  2.675970e+07  2.356474e+07
97    2.948267e+07  3.261287e+07  2.740097e+07
98    1.372437e+07  1.459991e+07  1.150465e+07
99    1.568000e+02  2.631143e+05  9.487876e+04

[81 rows x 3 columns]

In [27]:
dept_sales_change = dept_year_sales.assign(
    sales_change = lambda x: x[2012] - x[2010]
)[['sales_change']].sort_values('sales_change',ascending=False)
pd.set_option('display.max_rows', None)

dept_sales_change

Year  sales_change
Dept
87      3776524.49
48       417173.51
99        94721.96
96        55262.71
77         8546.89
47         3411.26
39           98.16
43            3.75
78         -858.15
45       -12441.16
60       -21172.19
51       -24047.82
50       -71784.06
56      -221428.81
54      -308851.40
65      -362696.45
19      -402565.30
37      -424837.95
42      -443841.89
28      -444586.59
36      -595664.82
27      -618840.40
49      -683126.91
35      -693049.55
41      -710195.86
83      -960341.15
52      -973321.52
12     -1040337.43
31     -1254382.07
3      -1308040.43
58     -1365064.57
44     -1382782.14
20     -1535935.86
30     -1609727.14
85     -1711828.54
71     -1744150.20
29     -2048004.84
80     -2060403.45
97     -2081694.19
59     -2136570.42
98     -2219716.29
67     -2411615.78
93     -2439522.55
16     -2488419.50
81     -2528656.67
82     -2646303.64
24     -2866268.35
9      -2946482.44
21     -3016696.01
33     -3120373.34
25     -3357640.01
10     -3424155.35
22     -3502354.38
26     -3644779.58
90     -3689516.78
32     -3789202.66
46     -3845806.79
74     -3957072.85
34     -4128225.07
92     -4208134.91
94     -4382932.66
4      -4573935.13
11     -4853170.78
91     -4937207.79
17     -5115503.91
79     -5445771.99
6      -6423351.75
8      -6492279.50
40     -7215750.34
1      -7397606.62
14     -7603730.25
13     -7771781.40
38     -7853734.26
23     -8071489.57
2      -8999947.50
18    -10102708.31
55    -11342832.95
95    -11966649.67
5     -18299165.09
7     -20574458.69
72    -30201479.42

### Insight
Department 87 recorded the largest sales increase from 2010 to 2012, while Department 72 experienced the largest decline. Overall, most departments recorded lower sales in 2012 compared with 2010.

### Business Question
Which departments show the largest fluctuations in annual sales?

In [28]:
dept_year_std = (
    dept_year_sales
    .std(axis=1)
    .sort_values(ascending=False)
    .reset_index(name='yearly_sales_std')
)

dept_year_std

    Dept  yearly_sales_std
0     72      1.883571e+07
1     92      1.329808e+07
2      7      1.211009e+07
3     95      1.183930e+07
4     38      1.128942e+07
5      5      1.018290e+07
6     90      9.639842e+06
7      2      8.238258e+06
8     40      7.061695e+06
9     91      6.232114e+06
10    55      6.207451e+06
11    18      5.939032e+06
12    13      5.661512e+06
13     8      5.604921e+06
14    23      5.418356e+06
15    94      5.239955e+06
16     1      5.149119e+06
17     4      4.782876e+06
18    14      4.668006e+06
19    93      4.495477e+06
20    82      4.294342e+06
21    46      4.159544e+06
22    79      4.106217e+06
23    10      3.552268e+06
24    11      3.366332e+06
25     6      3.255026e+06
26    17      2.977830e+06
27    87      2.932971e+06
28    74      2.838659e+06
29    81      2.829855e+06
30    97      2.623466e+06
31     9      2.465322e+06
32    22      2.268971e+06
33    34      2.247800e+06
34    32      2.245605e+06
35    80      2.240463e+06
36    25      2.172660e+06
37    26      2.077258e+06
38    96      1.860766e+06
39    33      1.735115e+06
40    21      1.633343e+06
41     3      1.627401e+06
42    24      1.622165e+06
43    98      1.595532e+06
44    67      1.566560e+06
45    29      1.302050e+06
46    16      1.261051e+06
47    71      1.076448e+06
48    59      1.071789e+06
49    44      9.903862e+05
50    49      9.594570e+05
51    85      9.444158e+05
52    20      9.356905e+05
53    30      8.784984e+05
54    31      8.043989e+05
55    42      7.516265e+05
56    58      6.928005e+05
57    41      6.608856e+05
58    12      6.367887e+05
59    52      6.102681e+05
60    83      5.544715e+05
61    35      5.443759e+05
62    36      4.802245e+05
63    27      4.289181e+05
64    37      2.782340e+05
65    28      2.394796e+05
66    19      2.273356e+05
67    48      2.086519e+05
68    65      1.820456e+05
69    54      1.641289e+05
70    56      1.416916e+05
71    99      1.331804e+05
72    50      1.050490e+05
73    60      7.799240e+04
74    77      2.150224e+04
75    51      1.260030e+04
76    45      6.259419e+03
77    47      2.485743e+03
78    78      4.547806e+02
79    39      6.982354e+01
80    43      2.733429e+00

### Insight
Department 72 shows the highest variation in annual sales, followed by Departments 92 and 7. Department 43 shows the lowest variation across the three years.

### Business Question

Which departments combine high average sales with relatively low variability?

In [50]:
strong_stable_dept = (
    dept_risk
    .query("dept_avg > 20000 and dept_std < 30000")
    .sort_values('dept_avg', ascending=False).round(2)
)

strong_stable_dept

    Dept  dept_avg  dept_std    cv
36    38  61090.62  23966.91  0.39
57    65  45441.71   7086.89  0.16
38    40  44900.70  21903.88  0.49
1      2  43607.02  25176.76  0.58
72    91  33687.91  26247.46  0.78
75    94  33405.88  25405.56  0.76
12    13  30663.80  16237.53  0.53
7      8  30191.26  18189.72  0.60
74    93  27008.06  22593.65  0.84
3      4  25974.63  13261.14  0.51
6      7  24161.24  27985.08  1.16
21    23  23931.47  16035.20  0.67
64    79  21973.04  13730.02  0.62
4      5  21365.58  19988.45  0.94
8      9  20206.68  16695.73  0.83

### Insight
Several high-sales departments also show relatively high variability. Department 7 has the highest relative variability in this group, while Department 91 has the lowest CV among the selected departments.

### Buisness Question

Which departments have high sales but also high relative variability?

In [52]:
high_sales_high_variability = (
    dept_risk
    .query("dept_avg > 20000 and cv > 0.75")
    .sort_values('cv', ascending=False).round(2)
)

high_sales_high_variability

    Dept  dept_avg  dept_std    cv
6      7  24161.24  27985.08  1.16
4      5  21365.58  19988.45  0.94
60    72  50566.52  44710.98  0.88
74    93  27008.06  22593.65  0.84
8      9  20206.68  16695.73  0.83
72    91  33687.91  26247.46  0.78
75    94  33405.88  25405.56  0.76

### Insight
Among high-sales departments, Department 7 has the highest relative variability (CV 1.158). Department 72 also shows high variability while maintaining strong average weekly sales, indicating that these departments have less consistent sales performance.

## Buisness Question

Which departments consistently perform well across all three years?

In [31]:
dept_year_positive = dept_year_sales.gt(0).all(axis = 1)
consistant_departments = dept_year_sales[dept_year_positive]
consistant_departments

Year          2010          2011          2012
Dept
1     4.284353e+07  4.534931e+07  3.544593e+07
2     9.405293e+07  1.015053e+08  8.505299e+07
3     2.509114e+07  2.701822e+07  2.378310e+07
4     5.557729e+07  6.056611e+07  5.100335e+07
5     5.177156e+07  5.036340e+07  3.347240e+07
6     1.237954e+07  1.008493e+07  5.956193e+06
7     5.842404e+07  5.920394e+07  3.784958e+07
8     6.536836e+07  7.003633e+07  5.887608e+07
9     4.312974e+07  4.508026e+07  4.018326e+07
10    3.921423e+07  4.289309e+07  3.579007e+07
11    3.218926e+07  3.380392e+07  2.733609e+07
12    9.228136e+06  9.344185e+06  8.187799e+06
13    6.728259e+07  7.052816e+07  5.951081e+07
14    3.413632e+07  3.502576e+07  2.653259e+07
16    3.191970e+07  3.031971e+07  2.943128e+07
17    2.345061e+07  2.353410e+07  1.833511e+07
18    1.554719e+07  1.590581e+07  5.444486e+06
19    2.412333e+06  2.394082e+06  2.009768e+06
20    1.157589e+07  1.173379e+07  1.003996e+07
21    1.183476e+07  1.141181e+07  8.818067e+06
22    2.082589e+07  2.157368e+07  1.732354e+07
23    4.800848e+07  5.023485e+07  3.993699e+07
24    1.244356e+07  1.232673e+07  9.577296e+06
25    1.991965e+07  2.062956e+07  1.656201e+07
26    1.588014e+07  1.578451e+07  1.223536e+07
27    3.103706e+06  3.308765e+06  2.484865e+06
28    1.432578e+06  1.364585e+06  9.879910e+05
29    1.056289e+07  1.093182e+07  8.514888e+06
30    7.864722e+06  7.669664e+06  6.254995e+06
31    5.067522e+06  5.312722e+06  3.813140e+06
32    1.476493e+07  1.495831e+07  1.097572e+07
33    1.274983e+07  1.250468e+07  9.629458e+06
34    2.929150e+07  2.876885e+07  2.516327e+07
35    5.261722e+06  5.642381e+06  4.568672e+06
36    3.650176e+06  4.004827e+06  3.054511e+06
37    2.781083e+06  2.879915e+06  2.356245e+06
38    1.288553e+08  1.432613e+08  1.210016e+08
39    3.892000e+01  1.980000e+00  1.370800e+02
40    9.641509e+07  1.033216e+08  8.919934e+07
41    3.566715e+06  4.177032e+06  2.856519e+06
42    1.088041e+07  1.190231e+07  1.043657e+07
43    1.750000e+00  7.070000e+00  5.500000e+00
44    8.765188e+06  9.302019e+06  7.382406e+06
45    2.079783e+04  1.578313e+04  8.356670e+03
46    4.257488e+07  4.704046e+07  3.872907e+07
48    5.693381e+05  7.869548e+05  9.865116e+05
49    1.201488e+07  1.322627e+07  1.133175e+07
50    1.363291e+06  1.498399e+06  1.291507e+06
51    2.438996e+04  5.840730e+03  3.421400e+02
52    4.303046e+06  4.454167e+06  3.329724e+06
54    3.586228e+05  1.079005e+05  4.977137e+04
55    2.420469e+07  2.290391e+07  1.286186e+07
56    7.563504e+06  7.605944e+06  7.342075e+06
58    6.169731e+06  5.281367e+06  4.804666e+06
59    2.531748e+06  1.313469e+06  3.951774e+05
60    6.343142e+05  7.575648e+05  6.131420e+05
65    2.356594e+06  2.147673e+06  1.993897e+06
67    1.658868e+07  1.711504e+07  1.417706e+07
71    1.063541e+07  1.085635e+07  8.891262e+06
72    1.105091e+08  1.149085e+08  8.030760e+07
74    3.039732e+07  3.194442e+07  2.644025e+07
77    7.970000e+00  4.078144e+04  8.554860e+03
78    1.087670e+03  3.975200e+02  2.295200e+02
79    4.808053e+07  5.068125e+07  4.263476e+07
80    2.380621e+07  2.622204e+07  2.174581e+07
81    3.298665e+07  3.610738e+07  3.045800e+07
82    3.214679e+07  3.789979e+07  2.950049e+07
83    6.983036e+06  6.983100e+06  6.022695e+06
85    5.195689e+06  5.031147e+06  3.483860e+06
87    2.540269e+07  3.117816e+07  2.917922e+07
90    9.340488e+07  1.079482e+08  8.971536e+07
91    7.142537e+07  7.886816e+07  6.648817e+07
92    1.558376e+08  1.764763e+08  1.516294e+08
93    5.195455e+07  5.822909e+07  4.951503e+07
94    6.274761e+07  6.880016e+07  5.836468e+07
95    1.498584e+08  1.615699e+08  1.378918e+08
96    2.350948e+07  2.675970e+07  2.356474e+07
97    2.948267e+07  3.261287e+07  2.740097e+07
98    1.372437e+07  1.459991e+07  1.150465e+07
99    1.568000e+02  2.631143e+05  9.487876e+04

### Insight
There are 99 departments